import { admissionReply, type AdmissionDecision, type AdmissionGate } from './admission';
import { runAgent } from '../agent/engine';
import type { ModelProvider } from '../agent/provider';
import type { AgentRequest } from '../agent/types';
import { MAX_SYSTEM_PROMPT_CHARS } from '../agent/types';
import type { ConversationOrchestrator, ProcessingRepository } from './types';

// Conversational use-case (Phase 6): one claimed Telegram text update →
// default conversation → user message persisted → bounded history → Agent Core
// engine → injected ModelProvider (the AI Router in production) → assistant
// message persisted → completion state → text returned for delivery.
//
// Durable idempotency (approved policy):
// - markGenerating is durable BEFORE runAgent. After it succeeds this update
//   can never be regenerated by redelivery, even if this invocation crashes,
//   times out, or the provider outcome is lost. Provider execution is
//   therefore at-most-once per update (at-least-once per attempt only via the
//   router's internal failover, unchanged).
// - AI failure → markFailed (terminal): redelivery acknowledges without AI.
// - Success → assistant message persisted, then completed. A crash between
//   persist and complete leaves 'generating'; redelivery is non-retryable for
//   generation but delivery may reuse the persisted assistant message.
// - Telegram sendMessage is at-least-once externally; no exactly-once claim.
//
// This layer never logs content and never sees credentials (the router owns
// them). Failures surface as ConversationFlowError with generic kinds; the
// transport maps them to safe responses.

export const ORCHESTRATION_HISTORY_LIMIT = 20;

export type ConversationFlowErrorKind =
  | 'conversation_failed'
  | 'user_message_failed'
  | 'generating_mark_failed'
  | 'history_failed'
  | 'agent_failed'
  | 'assistant_message_failed'
  | 'completion_mark_failed';

/** Failures that occur BEFORE generation starts (before markGenerating): safe to release the claim so redelivery reprocesses from scratch. */
export const PRE_GENERATION_ERROR_KINDS: readonly ConversationFlowErrorKind[] = ['conversation_failed'];

export class ConversationFlowError extends Error {
  readonly kind: ConversationFlowErrorKind;

  constructor(kind: ConversationFlowErrorKind) {
    super(`Conversation flow error: ${kind}`);
    this.name = 'ConversationFlowError';
    this.kind = kind;
  }
}

export interface ConversationFlowDeps {
  admission: AdmissionGate;
  orchestrator: ConversationOrchestrator;
  processing: ProcessingRepository;
  /** The Agent Core provider port; the AI Router in production, a fake in tests. */
  provider: ModelProvider;
  /** Correlation id for Agent Core (already generated per webhook request). */
  requestId: string;
  /** Internal user id (resolved by the transport layer's upsert). */
  userId: number;
  /** Opaque Agent Core caller id (internal user id as string; not a credential). */
  agentUserId: string;
  /** Model identifier passed through to the router; router selects provider/credentials. */
  model: string;
  /** Application system prompt; the Agent Core bounds it (≤8k chars). */
  systemPrompt: string;
}

export interface ConversationFlowResult {
  state: 'completed' | 'reused' | 'rejected';
  assistantText: string;
  /** Set only when state is 'rejected': the durable admission decision. */
  decision?: AdmissionDecision;
}

/**
 * Runs the conversational path for one claimed update. Ordering is deliberate:
 * conversation resolution → ATOMIC markGenerating → user message → history →
 * AI → assistant message → completed. The atomic mark happens BEFORE any
 * message persistence and before the provider call, so concurrent deliveries
 * of the same update cannot both persist a user message or both generate:
 * exactly one wins the claimed→generating transition; the loser reuses the
 * durable result or fails closed without touching the AI.
 */
export async function handleUserTextMessage(
  updateId: number,
  text: string,
  deps: ConversationFlowDeps,
): Promise<ConversationFlowResult> {
  const { orchestrator, processing } = deps;
  const decision = await deps.admission.admit(deps.userId, updateId).catch(() => 'unavailable' as const);
  if (decision !== 'allowed') {
    return { state: 'rejected', assistantText: admissionReply(decision), decision };
  }

  const { conversation } = await orchestrator.resolveDefaultConversation(deps.userId).catch(() => {
    throw new ConversationFlowError('conversation_failed');
  });

  // Durable gate BEFORE persisting/generating: after this succeeds, this
  // update can never be regenerated by redelivery (approved policy).
  const marked = await processing.markGenerating(updateId, conversation.id).catch(() => false);
  if (!marked) {
    // Lost the race or a terminal state exists: reuse the durable result if
    // one is present; never regenerate.
    const reused = await getCompletedAssistantText(updateId, deps).catch(() => null);
    if (reused !== null) return { state: 'reused', assistantText: reused };
    throw new ConversationFlowError('generating_mark_failed');
  }

  await orchestrator.appendMessage(deps.userId, conversation.id, { role: 'user', content: text }).catch(() => {
    throw new ConversationFlowError('user_message_failed');
  });

  const history = await orchestrator.getContext(deps.userId, conversation.id, ORCHESTRATION_HISTORY_LIMIT).catch(() => {
    throw new ConversationFlowError('history_failed');
  });

  let assistantText: string;
  try {
    const response = await runAgent(buildAgentRequest(deps, history), deps.provider);
    assistantText = response.text;
  } catch {
    // Terminal failure: the update never regenerates (approved policy).
    await processing.markFailed(updateId).catch(() => undefined);
    throw new ConversationFlowError('agent_failed');
  }

  const assistant = await orchestrator.appendMessage(deps.userId, conversation.id, { role: 'assistant', content: assistantText }).catch(() => {
    throw new ConversationFlowError('assistant_message_failed');
  });

  const completed = await processing.completeWithAssistantMessage(updateId, assistant.id).catch(() => false);
  if (!completed) throw new ConversationFlowError('completion_mark_failed');

  return { state: 'completed', assistantText };
}

function buildAgentRequest(deps: ConversationFlowDeps, history: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>): AgentRequest {
  return {
    requestId: deps.requestId,
    userId: deps.agentUserId,
    messages: history,
    config: {
      systemPrompt: deps.systemPrompt.slice(0, MAX_SYSTEM_PROMPT_CHARS),
      model: deps.model,
    },
  };
}

/**
 * Redelivery path for an update whose durable state is 'completed':
 * returns the persisted assistant text for re-delivery. Never calls the AI.
 * Returns null when the durable result is missing/unreadable (caller treats
 * the update as processed-and-unrecoverable and acknowledges without sending).
 */
export async function getCompletedAssistantText(
  updateId: number,
  deps: Pick<ConversationFlowDeps, 'processing' | 'orchestrator' | 'userId'>,
): Promise<string | null> {
  const record = await deps.processing.getProcessingRecord(updateId).catch(() => null);
  if (record === null || record.state !== 'completed') return null;
  if (record.conversationId === null || record.assistantMessageId === null) return null;
  return deps.orchestrator.getMessageText(deps.userId, record.conversationId, record.assistantMessageId).catch(() => null);
}
