import { admissionReply, type AdmissionDecision, type AdmissionGate } from './admission';
import { runAgent } from '../agent/engine';
import type { ModelProvider } from '../agent/provider';
import type { AgentRequest, AgentResponse } from '../agent/types';
import { MAX_SYSTEM_PROMPT_CHARS, DEFAULT_OUTPUT_TOKENS } from '../agent/types';
import { runAgentWithTools } from '../tools/agent-loop';
import { ToolRegistry } from '../tools/registry';
import { resolveRoutingProfile, researchToolNames } from '../ai/routing-profiles';
import type { ProviderDirectorySnapshot } from './production';
import type { ConversationOrchestrator, ProcessingRepository } from './types';

// Conversational use-case (Phase 6): one claimed Telegram text update →
// default conversation → user message persisted → bounded history → Agent Core
// engine → injected ModelProvider (the AI Router in production) → assistant
// message persisted → completion state → text returned for delivery.
//
// Durable idempotency (approved policy):
// - markGenerating is durable BEFORE runAgent. After it succeeds this update
//   can never be regenerated by redelivery, even if this invocation crashes,
//   times out, or the provider outcome is lost. Provider execution is
//   therefore at-most-once per update (at-least-once per attempt only via the
//   router's internal failover, unchanged).
// - AI failure → markFailed (terminal): redelivery acknowledges without AI.
// - Success → assistant message persisted, then completed. A crash between
//   persist and complete leaves 'generating'; redelivery is non-retryable for
//   generation but delivery may reuse the persisted assistant message.
// - Telegram sendMessage is at-least-once externally; no exactly-once claim.
//
// This layer never logs content and never sees credentials (the router owns
// them). Failures surface as ConversationFlowError with generic kinds; the
// transport maps them to safe responses.

export const ORCHESTRATION_HISTORY_LIMIT = 20;

export type ConversationFlowErrorKind =
  | 'conversation_failed'
  | 'user_message_failed'
  | 'generating_mark_failed'
  | 'history_failed'
  | 'agent_failed'
  | 'assistant_message_failed'
  | 'completion_mark_failed';

/** Failures that occur BEFORE generation starts (before markGenerating): safe to release the claim so redelivery reprocesses from scratch. */
export const PRE_GENERATION_ERROR_KINDS: readonly ConversationFlowErrorKind[] = ['conversation_failed'];

export class ConversationFlowError extends Error {
  readonly kind: ConversationFlowErrorKind;

  constructor(kind: ConversationFlowErrorKind) {
    super(`Conversation flow error: ${kind}`);
    this.name = 'ConversationFlowError';
    this.kind = kind;
  }
}

export interface ConversationFlowDeps {
  admission: AdmissionGate;
  orchestrator: ConversationOrchestrator;
  processing: ProcessingRepository;
  /** The Agent Core provider port; the AI Router in production, a fake in tests. */
  provider: ModelProvider;
  /** Correlation id for Agent Core (already generated per webhook request). */
  requestId: string;
  /** Internal user id (resolved by the transport layer's upsert). */
  userId: number;
  /** Opaque Agent Core caller id (internal user id as string; not a credential). */
  agentUserId: string;
  /** Model identifier passed through to the router; router selects provider/credentials. */
  model: string;
  /** Application system prompt; the Agent Core bounds it (≤8k chars). */
  systemPrompt: string;
  /** Smart-routing profile override; DEFAULT when omitted. */
  routingProfile?: unknown;
  /** Records successful generations for cost analytics; absent in tests. */
  usageRecorder?: UsageRecorder;
  /** Semantic-memory recall hook; absent when memory is disabled. */
  memoryRecall?: MemoryRecallHook;
  /** Optional research-mode web tool registry (read-only web tools only). */
  researchTools?: { names: readonly string[]; executor: ToolExecutor } | undefined;
  /**
   * Non-secret provider-directory snapshot for routing-profile resolution.
   * When present, profiles resolve against the same directory the router
   * uses; when absent, profiles fall back to router-default semantics.
   */
  directorySnapshot?: ProviderDirectorySnapshot | undefined;
}

/** Owner-scoped sink for one successful generation's provider-reported usage. */
export interface UsageRecorder {
  record(input: { providerId: string; vendorModel: string; requestId: string; inputTokens: number; outputTokens: number }): Promise<void>;
}

/** Owner-scoped semantic-memory recall hook. Returns bounded context text. */
export type MemoryRecallHook = (query: string) => Promise<string>;

/** Bounded executor for research-mode web tools (registry-namespaced). */
export type ToolExecutor = (name: string, input: unknown) => Promise<{ kind: string; content: string }>;

export interface ConversationFlowResult {
  state: 'completed' | 'reused' | 'rejected';
  assistantText: string;
  /** Set only when state is 'rejected': the durable admission decision. */
  decision?: AdmissionDecision;
}

/**
 * Runs the conversational path for one claimed update. Ordering is deliberate:
 * conversation resolution → ATOMIC markGenerating → user message → history →
 * AI → assistant message → completed. The atomic mark happens BEFORE any
 * message persistence and before the provider call, so concurrent deliveries
 * of the same update cannot both persist a user message or both generate:
 * exactly one wins the claimed→generating transition; the loser reuses the
 * durable result or fails closed without touching the AI.
 */
export async function handleUserTextMessage(
  updateId: number,
  text: string,
  deps: ConversationFlowDeps,
): Promise<ConversationFlowResult> {
  const { orchestrator, processing } = deps;
  const decision = await deps.admission.admit(deps.userId, updateId).catch(() => 'unavailable' as const);
  if (decision !== 'allowed') {
    return { state: 'rejected', assistantText: admissionReply(decision), decision };
  }

  const { conversation } = await orchestrator.resolveDefaultConversation(deps.userId).catch(() => {
    throw new ConversationFlowError('conversation_failed');
  });

  // Durable gate BEFORE persisting/generating: after this succeeds, this
  // update can never be regenerated by redelivery (approved policy).
  const marked = await processing.markGenerating(updateId, conversation.id).catch(() => false);
  if (!marked) {
    // Lost the race or a terminal state exists: reuse the durable result if
    // one is present; never regenerate.
    const reused = await getCompletedAssistantText(updateId, deps).catch(() => null);
    if (reused !== null) return { state: 'reused', assistantText: reused };
    throw new ConversationFlowError('generating_mark_failed');
  }

  await orchestrator.appendMessage(deps.userId, conversation.id, { role: 'user', content: text }).catch(() => {
    throw new ConversationFlowError('user_message_failed');
  });

  const history = await orchestrator.getContext(deps.userId, conversation.id, ORCHESTRATION_HISTORY_LIMIT).catch(() => {
    throw new ConversationFlowError('history_failed');
  });

  // Phase 10: optional in-flow enhancements, each independently absent-safe.
  // Routing profiles only rewrite `model` for the provider port; the router
  // resolves it with identical semantics. Memory context is bounded,
  // untrusted-delimited data. Research web tools come from the read-only
  // allowlist and execute through the bounded tool registry.
  const providers = await listProvidersForRouting(deps).catch(() => [] as Array<{ id: string; enabled: boolean; weight: number }>);
  const routing = resolveRoutingProfile(deps.routingProfile, { model: deps.model, providers });
  const memoryBlock = deps.memoryRecall === undefined ? '' : await deps.memoryRecall(text).catch(() => '');
  const toolMessages = memoryBlock.length === 0 ? history : [...history.slice(0, -1), { role: history[history.length - 1]?.role ?? 'user' as const, content: `${history[history.length - 1]?.content ?? text}\n\n${memoryBlock}` }];
  let assistantText: string;
  let agentResponse: AgentResponse | null = null;
  try {
    if (routing.enableWebTools && deps.researchTools !== undefined) {
      const registry = new ToolRegistry();
      for (const name of researchToolNames(deps.researchTools.names)) {
        registry.register({ name, description: `${name} (research mode)`, inputSchema: {}, execute: (input) => deps.researchTools?.executor(name, input).then((result) => ({ kind: 'success' as const, content: result.content })) ?? Promise.resolve({ kind: 'upstream_error' as const, content: `${name} unavailable` }) });
      }
      assistantText = await runAgentWithTools(toolMessages, {
        provider: deps.provider,
        registry,
        requestId: deps.requestId,
        agentUserId: deps.agentUserId,
        model: routing.model,
        systemPrompt: deps.systemPrompt,
      });
    } else {
      agentResponse = await runAgent(buildAgentRequest(deps, toolMessages, routing), deps.provider);
      assistantText = agentResponse.text;
    }
  } catch (agentError) {
    // TEMP-DIAGNOSTIC (remove after production triage): logs ONLY bounded,
    // non-secret metadata — error name, sanitized generic message (ProviderError
    // messages are constant strings like 'Provider error: upstream'), and
    // httpStatus when present. Never prompt/response content, keys, or bodies.
    const diag = agentError instanceof Error
      ? {
          name: agentError.name,
          message: String(agentError.message).replace(/[^\x20-\x7E]/g, '?').slice(0, 120),
          ...(('code' in agentError && typeof (agentError as { code?: unknown }).code === 'string') ? { code: (agentError as { code: string }).code } : {}),
          ...(('httpStatus' in agentError && typeof (agentError as { httpStatus?: unknown }).httpStatus === 'number') ? { http_status: (agentError as { httpStatus: number }).httpStatus } : {}),
          ...(('phase' in agentError && typeof (agentError as { phase?: unknown }).phase === 'string') ? { failure_phase: (agentError as { phase: string }).phase } : {}),
          ...(('detail' in agentError && typeof (agentError as { detail?: unknown }).detail === 'string') ? { detail: String((agentError as { detail: string }).detail).slice(0, 200) } : {}),
        }
      : { name: typeof agentError };
    console.error(JSON.stringify({ event: 'agent_stage_failed', request_id: deps.requestId, ...diag }));
    // Terminal failure: the update never regenerates (approved policy).
    await processing.markFailed(updateId).catch(() => undefined);
    throw new ConversationFlowError('agent_failed');
  }
  if (deps.usageRecorder !== undefined) {
    const usage = extractAgentUsage(agentResponse);
    if (usage !== null) {
      await deps.usageRecorder.record({
        providerId: usage.providerId,
        vendorModel: usage.vendorModel,
        requestId: deps.requestId,
        inputTokens: usage.inputTokens,
        outputTokens: usage.outputTokens,
      }).catch(() => undefined);
    }
  }

  const assistant = await orchestrator.appendMessage(deps.userId, conversation.id, { role: 'assistant', content: assistantText }).catch(() => {
    throw new ConversationFlowError('assistant_message_failed');
  });

  const completed = await processing.completeWithAssistantMessage(updateId, assistant.id).catch(() => false);
  if (!completed) throw new ConversationFlowError('completion_mark_failed');

  return { state: 'completed', assistantText };
}

function buildAgentRequest(
  deps: ConversationFlowDeps,
  history: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>,
  routing?: { model: string; outputMultiplier: 1 | 2 },
): AgentRequest {
  return {
    requestId: deps.requestId,
    userId: deps.agentUserId,
    messages: history,
    config: {
      systemPrompt: deps.systemPrompt.slice(0, MAX_SYSTEM_PROMPT_CHARS),
      model: routing?.model ?? deps.model,
      maxOutputTokens: routing?.outputMultiplier === 2 ? DEFAULT_OUTPUT_TOKENS * 2 : undefined,
    },
  };
}

/**
 * Best-effort provider listing for routing-profile resolution over the
 * explicit ProviderDirectorySnapshot port. Failures yield an empty list
 * (profiles then fall back to router semantics). The snapshot carries only
 * id/enabled/weight — no credentials, base URLs, or secrets — and malformed
 * rows are dropped, never trusted.
 */
async function listProvidersForRouting(deps: ConversationFlowDeps): Promise<Array<{ id: string; enabled: boolean; weight: number }>> {
  const snapshot = deps.directorySnapshot;
  if (snapshot === undefined) return [];
  const entries = await snapshot.listRoutingProviders().catch(() => [] as ReadonlyArray<{ id: string; enabled: boolean; weight: number }>);
  if (!Array.isArray(entries)) return [];
  const out: Array<{ id: string; enabled: boolean; weight: number }> = [];
  for (const entry of entries) {
    if (typeof entry.id !== 'string' || !/^[a-z0-9-]{1,64}$/.test(entry.id)) continue;
    out.push({
      id: entry.id,
      enabled: entry.enabled === true,
      weight: typeof entry.weight === 'number' && Number.isSafeInteger(entry.weight) ? entry.weight : 0,
    });
  }
  return out;
}

/**
 * Extracts provider-reported usage from a successful response only. Research
 * mode's tool loop summarizes many calls into one final text with no single
 * attribution, so its usage is deliberately not recorded (fail closed rather
 * than misattribute).
 */
function extractAgentUsage(response: AgentResponse | null): { providerId: string; vendorModel: string; inputTokens: number; outputTokens: number } | null {
  if (response === null || response === undefined) return null;
  const usage = response.usage;
  if (usage === undefined) return null;
  const inputTokens = usage.inputTokens ?? 0;
  const outputTokens = usage.outputTokens ?? 0;
  if (!Number.isSafeInteger(inputTokens) || inputTokens < 0 || !Number.isSafeInteger(outputTokens) || outputTokens < 0) return null;
  const separator = response.model.indexOf(':');
  const providerId = separator > 0 ? response.model.slice(0, separator) : 'unknown';
  if (!/^[a-z0-9-]{1,64}$/.test(providerId)) return null;
  return { providerId, vendorModel: response.model.slice(0, 128), inputTokens, outputTokens };
}

/**
 * Redelivery path for an update whose durable state is 'completed':
 * returns the persisted assistant text for re-delivery. Never calls the AI.
 * Returns null when the durable result is missing/unreadable (caller treats
 * the update as processed-and-unrecoverable and acknowledges without sending).
 */
export async function getCompletedAssistantText(
  updateId: number,
  deps: Pick<ConversationFlowDeps, 'processing' | 'orchestrator' | 'userId'>,
): Promise<string | null> {
  const record = await deps.processing.getProcessingRecord(updateId).catch(() => null);
  if (record === null || record.state !== 'completed') return null;
  if (record.conversationId === null || record.assistantMessageId === null) return null;
  return deps.orchestrator.getMessageText(deps.userId, record.conversationId, record.assistantMessageId).catch(() => null);
}
